DROP DATABASE IF EXISTS golf;
CREATE DATABASE golf;

USE golf;

CREATE TABLE golfers (
    id INTO UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    player VARCHAR(30) UNIQUE NOT NULL,
    score INT DEFAULT (0)
);